//
//  HomeViewController.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: UITabBarController, HomeViewProtocol {

    var presenter: HomePresenterProtocol?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    convenience init() {
        self.init(nibName: nil, bundle: nil)
        self.view.backgroundColor = .black
        self.presenter?.setupViewControllers()
    }
    
    required init?(coder: NSCoder) { return nil }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .black
        debugPrint(self.view.bounds.size)
    }
    
    func display(_ viewControllers: [UIViewController]) {
        self.viewControllers = viewControllers
        let title = ["TV Shows", "Profile"]
        let image = ["rectangle.stack.fill", "star.fill"]
        
        var cont = 0
        if let tabBarItems = tabBar.items {
            for item in tabBarItems {
                item.title = title[cont]
                item.image = UIImage(systemName: image[cont])
                cont += 1
            }
        }
    }
}
