//
//  LoginPresenter.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {

    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func setSession(session: String) {
        view?.showHome(session: session)
    }
    
    func willGetLogin(username: String, password: String, requestToken: String) {
        
    }

    func willGetRequestToken(username: String, password: String) {
        interactor?.getRequestToken(username: username, password: password)
    }
    
    func willGetSessionNew(requestToken: String) {
        interactor?.getSessionNew(requestToken: requestToken)
    }
    
    func mostrarAlerta(mensaje: String) {
        view?.mostrarAlerta(mensaje: mensaje)
    }
    
    func willGoingToHome() {
        router.goingToHome()
    }

}
