//
//  LoginViewController.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {
    
    // MARK: - Properties
    var presenter: LoginPresenterProtocol?
    
    let attributes = [
        NSAttributedString.Key.font : UIFont.systemFont(ofSize: 16, weight: .bold)
    ]
    
    lazy var stack: UIStackView = {
        let stack = UIStackView()
        stack.alignment = .fill
        stack.distribution = .fill
        stack.axis = .vertical
        stack.spacing = 20
        stack.translatesAutoresizingMaskIntoConstraints = false
        return stack
    }()
    
    lazy var txtUser: UITextField = {
        let txtUser = UITextField()
        txtUser.borderStyle = .roundedRect
        txtUser.attributedPlaceholder = NSAttributedString(string: "Username", attributes: attributes)
        txtUser.translatesAutoresizingMaskIntoConstraints = false
        return txtUser
    }()
    
    lazy var txtPassword: UITextField = {
        let txtPassword = UITextField()
        txtPassword.borderStyle = .roundedRect
        txtPassword.attributedPlaceholder = NSAttributedString(string: "Password", attributes: attributes)
        txtPassword.translatesAutoresizingMaskIntoConstraints = false
        return txtPassword
    }()
    
    lazy var btnLogin: UIButton = {
        let btnLogin = UIButton(type: .roundedRect)
        btnLogin.setTitle("Log in", for: .normal)
        btnLogin.titleLabel?.font = UIFont.systemFont(ofSize: 18, weight: .bold)
        btnLogin.backgroundColor = .backgroundBtn()
        btnLogin.tintColor = .white
        btnLogin.addTarget(self, action: #selector(btnLoginAction(_:)), for: .touchUpInside)
        return btnLogin
    }()
    
    lazy var lblError: UILabel = {
        let lblError = UILabel()
        lblError.font = UIFont.systemFont(ofSize: 14, weight: .bold)
        lblError.text = "fjkhsbjfhjsfhkj fhkfhdshfjkshf fhskjfhkjdfh jshfjkdhfj jdkadah"
        lblError.textColor = .colorError()
//        lblError.textAlignment = .center
        lblError.numberOfLines = 0
        lblError.translatesAutoresizingMaskIntoConstraints = false
        return lblError
    }()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.configView()
    }
    
    // MARK: - Actions
    @objc func btnLoginAction(_ sender: Any) {
        debugPrint("Press button")
        let headers = [
          "content-type": "application/json;charset=utf-8",
          "authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhZTc0Y2Y3Y2IwNDdkOGE4MWRiYjcxYWNkMmYxZTVmYSIsInN1YiI6IjYwNWE4MjA4NDdjOWZiMDA2YWJmMzYzNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1cO8-Gn_S7fPoaNO-7LbnJpe-gXbTRlL5OKzxPsH4cY"
        ]
        let parameters = ["redirect_to": "http://www.themoviedb.org/"]

        let postData = try? JSONSerialization.data(withJSONObject: parameters, options: [])

        let request = NSMutableURLRequest(url: NSURL(string: "https://api.themoviedb.org/4/auth/request_token")! as URL,
                                          cachePolicy: .useProtocolCachePolicy,
                                            timeoutInterval: 10.0)
        request.httpMethod = "POST"
        request.allHTTPHeaderFields = headers
        request.httpBody = postData

        let session = URLSession.shared
        let dataTask = session.dataTask(with: request as URLRequest, completionHandler: { (data, response, error) -> Void in
          if (error != nil) {
            debugPrint(error)
          } else {
              let httpResponse = response as? HTTPURLResponse
            debugPrint(httpResponse)
              guard let data = data else { return }
              do {
                  let object = try JSONDecoder().decode(TokenNewResponse.self, from: data)
                  debugPrint(object)
//                  completion(APIResult.success(object))
              } catch {
                  print("error: ", error)
              }
          }
        })

        dataTask.resume()
    }
    
}

// MARK: - UI Setup
extension LoginViewController {
    func configView() {
        self.view.backgroundColor = .black
        
        stack.addArrangedSubview(txtUser)
        stack.addArrangedSubview(txtPassword)
        stack.addArrangedSubview(btnLogin)
        
        view.addSubview(stack)
        view.addSubview(lblError)
        
        txtUser.heightAnchor.constraint(equalToConstant: 50).isActive = true
        txtPassword.heightAnchor.constraint(equalToConstant: 50).isActive = true
        btnLogin.heightAnchor.constraint(equalToConstant: 50).isActive = true
        
        stack.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        stack.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
        stack.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 40).isActive = true
        stack.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -40).isActive = true
        
        lblError.topAnchor.constraint(equalTo: stack.bottomAnchor, constant: 20).isActive = true
        lblError.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 15).isActive = true
        lblError.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -15).isActive = true
    }
}
