//
//  TVShowViewController.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TVShowViewController: UIViewController, TVShowViewProtocol {

	var presenter: TVShowPresenterProtocol?
    var typeView: TypeView?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = .yellow
        self.title = "TV Show"
    }

}
