//
//  TVShowProtocols.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TVShowWireframeProtocol: class {

}
//MARK: Presenter -
protocol TVShowPresenterProtocol: class {

}

//MARK: Interactor -
protocol TVShowInteractorProtocol: class {

  var presenter: TVShowPresenterProtocol?  { get set }
}

//MARK: View -
protocol TVShowViewProtocol: class {

  var presenter: TVShowPresenterProtocol?  { get set }
}
