//
//  TVShowInteractor.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TVShowInteractor: TVShowInteractorProtocol {

    weak var presenter: TVShowPresenterProtocol?
}
