//
//  TVShowProtocols.swift
//  TVShow
//
//  Created Osvaldo Salas on 16/03/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TVShowWireframeProtocol: class {
    func goingToDetailShow(selectShow: Result)
}
//MARK: Presenter -
protocol TVShowPresenterProtocol: class {
    func createTVShow(selectedOption: MenuSGV)
    func selectShow(selectShow: Result)
    func didRecoverShows(shows:[Result])
    func showAlert(title: String, message: String)
}

//MARK: Interactor -
protocol TVShowInteractorProtocol: class {
    var presenter: TVShowPresenterProtocol?  { get set }
    func willRetriveShows(selectedOption: MenuSGV)
}

//MARK: View -
protocol TVShowViewProtocol: class {
    
    var presenter: TVShowPresenterProtocol?  { get set }
    func succesShows(shows:[Result])
    func showAlert(title: String, message: String)
}
